name: Deployment

concurrency: production

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Debug env
        run: |
          env | sort

      - name: Setup env
        run: |
          echo "DEBUG"

      - name: Create release ticket
        run: |
          echo "Create release ticket"
          echo "Share ticket number to deployment jobs below"

  deployment-staging:
    runs-on: ubuntu-latest
    needs: create-release
    environment: staging
    steps:
      - uses: actions/checkout@v4

      - name: Files
        run: |
          ls -lR

      - name: Deploy ENV
        run: |
          env | sort

      - name: Deploy PR
        run: |
          git rev-parse HEAD
          git status

      - name: Deploy to staging
        run: |
          echo "DEPLOYING TO STAGING"

          
  deployment-production:
    runs-on: ubuntu-latest
    needs: deployment-staging
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Files
        run: |
          ls -lR

      - name: Deploy ENV
        run: |
          env | sort

      - name: Deploy PR
        run: |
          git rev-parse HEAD
          git status

      - name: Deploy to production
        run: |
          echo "DEPLOYING TO PRODUCTION"
