name: Testing

on: [push]

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install .
      - name: Test with pytest
        run: |
          pytest --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
