name: Testing

on: [push]

jobs:
  testing:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      checks: write
      pull-requests: write
      id-token: write
      statuses: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install .

      - name: Test with pytest
        run: |
          pytest \
              --junitxml=junit/test-results.xml \
              --cov=com --cov-report=xml --cov-report=html \
              --ctrf ctrf/report.json

      - name: Publish Test Report
        uses: ctrf-io/github-test-reporter@v1
        with:
          report-path: './ctrf/*.json'

          summary-report: true
          github-report: true
          test-report: true
          test-list-report: true
          failed-report: true
          fail-rate-report: true
          flaky-report: true
          flaky-rate-report: rue
          failed-folded-report: true
          previous-results-report: true
          insights-report: true
          pull-request-report: true
          commit-report: true

          pull-request: true
          status-check: false
          update-comment: true
          overwrite-comment: true

          comment-tag: '${{ github.workflow }}-${{ github.job }}'

          upload-artifact: true
        env:
          GITHUB_TOKEN: ${{ github.token }}
        if: always()
