name: Testing

on: [push]

jobs:
  testing:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      checks: write
      pull-requests: write
      id-token: write
      statuses: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install .

      - name: Test with pytest
        run: |
          pytest \
              --junitxml=junit/test-results.xml \
              --cov=com --cov-report=xml --cov-report=html \
              --ctrf ctrf/report.json

      - name: Publish Test Report
        uses: ctrf-io/github-test-reporter@v1
        with:
          report-path: './ctrf/*.json'
          pull-request-report: true
          update-comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.TESTGITHUB_TOKEN }}
        if: always()
